2022-08-10 12:41:07.546197: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-10 12:41:07.546254: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/wittmann/Desktop/c1terminal-algo/python-algo-1/algo_strategy.py", line 7, in <module>
    import tensorflow
  File "/home/wittmann/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 479, in <module>
    keras._load()
  File "/home/wittmann/.local/lib/python3.8/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/wittmann/.local/lib/python3.8/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/wittmann/.local/lib/python3.8/site-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/home/wittmann/.local/lib/python3.8/site-packages/keras/metrics.py", line 26, in <module>
    from keras import activations
  File "/home/wittmann/.local/lib/python3.8/site-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/home/wittmann/.local/lib/python3.8/site-packages/keras/layers/__init__.py", line 27, in <module>
    from keras.engine.base_preprocessing_layer import PreprocessingLayer
  File "/home/wittmann/.local/lib/python3.8/site-packages/keras/engine/base_preprocessing_layer.py", line 19, in <module>
    from keras.engine import data_adapter
  File "/home/wittmann/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py", line 37, in <module>
    import pandas as pd  # pylint: disable=g-import-not-at-top
  File "/home/wittmann/.local/lib/python3.8/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/home/wittmann/.local/lib/python3.8/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/wittmann/.local/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/wittmann/.local/lib/python3.8/site-packages/pandas/util/version/__init__.py", line 92, in <module>
    SubLocalType = Union[InfiniteTypes, int, str]
  File "/usr/lib/python3.8/typing.py", line 258, in inner
    return cached(*args, **kwds)
  File "/usr/lib/python3.8/typing.py", line 362, in __getitem__
    return _GenericAlias(self, parameters)
  File "/usr/lib/python3.8/typing.py", line 660, in __init__
    self._inst = inst
  File "/usr/lib/python3.8/typing.py", line 763, in __setattr__
    if _is_dunder(attr) or attr in ('_name', '_inst', '_special'):
KeyboardInterrupt
